const useIndustryCategories = () => {
    const categories = [
        { name: `Agriculture`, banglaName: `কৃষি` },
        { name: `Agritech`, banglaName: `কৃষি প্রযুক্তি` },
        { name: `AI (Artificial Intelligence)`, banglaName: `কৃত্রিম বুদ্ধিমত্তা` },
        { name: `Aerospace`, banglaName: `বিমানচালনা` },
        { name: `Agricultural Engineering`, banglaName: `কৃষি প্রকৌশল` },
        { name: `Apparel`, banglaName: `পোশাক` },
        { name: `Artificial Organs`, banglaName: `কৃত্রিম অঙ্গ` },
        { name: `Automotive`, banglaName: `যানবাহন` },
        { name: `Aviation`, banglaName: `বিমানচালনা` },
        { name: `Blockchain`, banglaName: `ব্লকচেইন` },
        { name: `Business Services`, banglaName: `ব্যবসা সেবা` },
        { name: `Clean Energy`, banglaName: `পরিষ্কার শক্তি` },
        { name: `Construction`, banglaName: `নির্মাণ` },
        { name: `Cybersecurity`, banglaName: `সাইবার সিকিউরিটি` },
        { name: `Data Science`, banglaName: `ডেটা সায়েন্স` },
        { name: `Digital Marketing`, banglaName: `ডিজিটাল মার্কেটিং` },
        { name: `E-commerce`, banglaName: `ই-কমার্স` },
        { name: `Education Technology`, banglaName: `শিক্ষা প্রযুক্তি` },
        { name: `Energy Storage`, banglaName: `শক্তি সংরক্ষণ` },
        { name: `Entertainment`, banglaName: `বিনোদন` },
        { name: `Environmental Engineering`, banglaName: `পরিবেশগত প্রকৌশল` },
        { name: `Finance`, banglaName: `আর্থিক` },
        { name: `Financial Technology (Fintech)`, banglaName: `আর্থিক প্রযুক্তি (ফিনটেক)` },
        { name: `Food & Beverage`, banglaName: `খাদ্য ও পানীয়` },
        { name: `Food Processing`, banglaName: `খাদ্য প্রক্রিয়াকরণ` },
        { name: `Gaming`, banglaName: `গেমিং` },
        { name: `Green Construction`, banglaName: `সবুজ নির্মাণ` },
        { name: `Healthcare`, banglaName: `স্বাস্থ্যসেবা` },
        { name: `Healthcare IT`, banglaName: `স্বাস্থ্যসেবা আইটি` },
        { name: `Heavy Industry`, banglaName: `ভারী শিল্প` },
        { name: `Hospitality`, banglaName: `অতিথেয়তা` },
        { name: `HR Tech`, banglaName: `এইচআর প্রযুক্তি` },
        { name: `Immersive Media`, banglaName: `ইমার্সিভ মিডিয়া` },
        { name: `Insurance`, banglaName: `বীমা` },
        { name: `Internet of Things (IoT)`, banglaName: `ইন্টারনেট অফ থিংস (আইওটি)` },
        { name: `IT Services`, banglaName: `আইটি সেবা` },
        { name: `LegalTech`, banglaName: `লিগ্যালটেক` },
        { name: `Logistics`, banglaName: `লজিস্টিকস` },
        { name: `Marine Engineering`, banglaName: `মেরিন প্রকৌশল` },
        { name: `Materials Science`, banglaName: `উপাদান বিজ্ঞান` },
        { name: `Media & Advertising`, banglaName: `মিডিয়া ও বিজ্ঞাপন` },
        { name: `Medical Devices`, banglaName: `চিকিৎসা যন্ত্রপাতি` },
        { name: `Nanotechnology`, banglaName: `ন্যানোপ্রযুক্তি` },
        { name: `Pharmaceuticals`, banglaName: `ফার্মাসিউটিক্যালস` },
        { name: `Renewable Energy`, banglaName: `নবায়নযোগ্য শক্তি` },
        { name: `Robotics`, banglaName: `রোবোটিক্স` },
        { name: `Space Exploration`, banglaName: `মহাকাশ অন্বেষণ` },
        { name: `Software Development`, banglaName: `সফটওয়্যার উন্নয়ন` },
        { name: `Telecommunications`, banglaName: `টেলিযোগাযোগ` },
        { name: `Telemedicine`, banglaName: `টেলিমেডিসিন` },
        { name: `Tourism`, banglaName: `পর্যটন` },
        { name: `Transportation`, banglaName: `পরিবহন` },
        { name: `Video Games`, banglaName: `ভিডিও গেমস` },
        { name: `Water Treatment`, banglaName: `জল পরিশোধন` },
        { name: `Artificial Intelligence in Medicine`, banglaName: `চিকিৎসায় কৃত্রিম বুদ্ধিমত্তা` },
        { name: `Big Data`, banglaName: `বিগ ডেটা` },
        { name: `Cloud Computing`, banglaName: `ক্লাউড কম্পিউটিং` },
        { name: `CleanTech`, banglaName: `ক্লিনটেক` },
        { name: `Creative Arts`, banglaName: `সৃজনশীল শিল্প` },
        { name: `Cyber-Physical Systems`, banglaName: `সাইবার-ফিজিক্যাল সিস্টেম` },
        { name: `Data Center`, banglaName: `ডেটা সেন্টার` },
        { name: `Deep Learning`, banglaName: `ডিপ লার্নিং` },
        { name: `Digital Health`, banglaName: `ডিজিটাল স্বাস্থ্য` },
        { name: `Drone Technology`, banglaName: `ড্রোন প্রযুক্তি` },
        { name: `E-Learning`, banglaName: `ই-লার্নিং` },
        { name: `Electric Vehicles`, banglaName: `বিদ্যুত্‍ যানবাহন` },
        { name: `Energy Efficiency`, banglaName: `শক্তি দক্ষতা` },
        { name: `Environmentally Friendly Packaging`, banglaName: `পরিবেশ বান্ধব প্যাকেজিং` },
        { name: `Financial Services`, banglaName: `আর্থিক সেবা` },
        { name: `Freelancing`, banglaName: `ফ্রিল্যান্সিং` },
        { name: `Gaming Technology`, banglaName: `গেমিং প্রযুক্তি` },
        { name: `Healthcare Data Analytics`, banglaName: `স্বাস্থ্যসেবা ডেটা বিশ্লেষণ` },
        { name: `High Performance Computing`, banglaName: `উচ্চ পারফরম্যান্স কম্পিউটিং` },
        { name: `Home Automation`, banglaName: `হোম অটোমেশন` },
        { name: `Hydrogen Fuel`, banglaName: `হাইড্রোজেন জ্বালানি` },
        { name: `Industrial Automation`, banglaName: `শিল্প স্বয়ংক্রিয়করণ` },
        { name: `Infrastructure`, banglaName: `অবকাঠামো` },
        { name: `Internet Marketing`, banglaName: `ইন্টারনেট মার্কেটিং` },
        { name: `IoT Security`, banglaName: `আইওটি সিকিউরিটি` },
        { name: `Machine Learning`, banglaName: `মেশিন লার্নিং` },
        { name: `Manufacturing`, banglaName: `উৎপাদন` },
        { name: `Medical Imaging`, banglaName: `চিকিৎসা চিত্রকল্প` },
        { name: `Mining`, banglaName: `খনি` },
        { name: `Mobile Technology`, banglaName: `মোবাইল প্রযুক্তি` },
        { name: `Nanomaterials`, banglaName: `ন্যানোমেটেরিয়ালস` },
        { name: `Nuclear Energy`, banglaName: `পারমাণবিক শক্তি` },
        { name: `Optical Technology`, banglaName: `অপটিক্যাল প্রযুক্তি` },
        { name: `Petrochemical`, banglaName: `পেট্রোকেমিক্যাল` },
        { name: `Pharmaceutical Manufacturing`, banglaName: `ফার্মাসিউটিক্যাল উৎপাদন` },
        { name: `Quantum Computing`, banglaName: `কোয়ান্টাম কম্পিউটিং` },
        { name: `Renewable Resources`, banglaName: `নবায়নযোগ্য সম্পদ` },
        { name: `Robotics Process Automation`, banglaName: `রোবটিক্স প্রক্রিয়া স্বয়ংক্রিয়করণ` },
        { name: `Semiconductor`, banglaName: `সেমিকন্ডাক্টর` },
        { name: `Smart Grids`, banglaName: `স্মার্ট গ্রিড` },
        { name: `Smart Home`, banglaName: `স্মার্ট হোম` },
        { name: `Solar Energy`, banglaName: `সৌর শক্তি` },
        { name: `Supply Chain`, banglaName: `সরবরাহ চেইন` },
        { name: `Sustainability`, banglaName: `টেকসইতা` },
        { name: `Telecom Infrastructure`, banglaName: `টেলিযোগাযোগ অবকাঠামো` },
        { name: `Transportation Technology`, banglaName: `পরিবহন প্রযুক্তি` },
        { name: `Water Purification`, banglaName: `পানির পরিশোধন` },
        { name: `Waste Management`, banglaName: `বর্জ্য ব্যবস্থাপনা` },
        { name: `Wearables`, banglaName: `ওয়্যারেবলস` },
        { name: `Wind Energy`, banglaName: `বায়ু শক্তি` },
        { name: `Zero Waste`, banglaName: `জিরো ওয়েস্ট` }
    ];
    return (categories);
};

export default useIndustryCategories;